import { Notification, Activity } from '@/types';

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-3',
    type: 'task_assigned',
    title: 'Neue Task zugewiesen',
    message: 'Du wurdest der Task "Homepage Redesign" zugewiesen',
    link: '/projects/project-1/tasks/task-2',
    read: false,
    createdAt: '2024-10-05T08:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-3',
    type: 'deadline_approaching',
    title: 'Deadline naht',
    message: 'Die Task "Bug: Navigation Dropdown" ist in 2 Tagen fällig',
    link: '/projects/project-1/tasks/task-6',
    read: false,
    createdAt: '2024-10-05T09:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-4',
    type: 'mention',
    title: 'Du wurdest erwähnt',
    message: 'Tom Developer hat dich in einem Kommentar erwähnt',
    link: '/projects/project-1/tasks/task-2',
    read: true,
    createdAt: '2024-10-04T14:45:00Z',
  },
  {
    id: 'notif-4',
    userId: 'user-1',
    type: 'task_status_changed',
    title: 'Task-Status geändert',
    message: 'Design System erstellen wurde auf "Done" gesetzt',
    link: '/projects/project-1/tasks/task-1',
    read: true,
    createdAt: '2024-10-03T16:30:00Z',
  },
  {
    id: 'notif-5',
    userId: 'user-2',
    type: 'comment_added',
    title: 'Neuer Kommentar',
    message: 'Sarah Designer hat einen Kommentar zur Task "Instagram Posts erstellen" hinzugefügt',
    link: '/projects/project-3/tasks/task-13',
    read: false,
    createdAt: '2024-10-03T11:00:00Z',
  },
  {
    id: 'notif-6',
    userId: 'user-3',
    type: 'deadline_approaching',
    title: 'Deadline naht',
    message: 'Die Task "User Authentication Flow" ist in 4 Tagen fällig',
    link: '/projects/project-2/tasks/task-9',
    read: true,
    createdAt: '2024-10-05T07:00:00Z',
  },
];

export const mockActivities: Activity[] = [
  // Recent activities
  {
    id: 'activity-1',
    projectId: 'project-1',
    taskId: 'task-2',
    userId: 'user-3',
    action: 'comment_added',
    metadata: { comment: 'Navigation ist jetzt implementiert' },
    createdAt: '2024-10-04T14:45:00Z',
  },
  {
    id: 'activity-2',
    projectId: 'project-1',
    taskId: 'task-3',
    userId: 'user-3',
    action: 'time_logged',
    metadata: { hours: 5, description: 'Analytics Integration' },
    createdAt: '2024-10-03T14:00:00Z',
  },
  {
    id: 'activity-3',
    projectId: 'project-1',
    taskId: 'task-6',
    userId: 'user-1',
    action: 'task_created',
    metadata: { title: 'Bug: Navigation Dropdown funktioniert nicht' },
    createdAt: '2024-10-03T15:20:00Z',
  },
  {
    id: 'activity-4',
    projectId: 'project-1',
    taskId: 'task-6',
    userId: 'user-1',
    action: 'task_assigned',
    metadata: { assignedTo: 'user-3' },
    createdAt: '2024-10-03T15:21:00Z',
  },
  {
    id: 'activity-5',
    projectId: 'project-2',
    taskId: 'task-9',
    userId: 'user-3',
    action: 'time_logged',
    metadata: { hours: 5, description: 'Social Login' },
    createdAt: '2024-10-03T14:00:00Z',
  },
  {
    id: 'activity-6',
    projectId: 'project-2',
    taskId: 'task-11',
    userId: 'user-4',
    action: 'comment_added',
    metadata: { comment: 'Dashboard und Profile Screens sind jetzt fertig' },
    createdAt: '2024-10-02T10:00:00Z',
  },
  {
    id: 'activity-7',
    projectId: 'project-3',
    taskId: 'task-13',
    userId: 'user-4',
    action: 'time_logged',
    metadata: { hours: 4, description: 'Design 10 Posts' },
    createdAt: '2024-10-01T13:00:00Z',
  },
  {
    id: 'activity-8',
    projectId: 'project-4',
    taskId: 'task-17',
    userId: 'user-3',
    action: 'task_status_changed',
    metadata: { from: 'todo', to: 'in_progress' },
    createdAt: '2024-10-02T09:00:00Z',
  },
  {
    id: 'activity-9',
    projectId: 'project-1',
    taskId: 'task-1',
    userId: 'user-4',
    action: 'task_status_changed',
    metadata: { from: 'in_progress', to: 'done' },
    createdAt: '2024-02-10T16:30:00Z',
  },
  {
    id: 'activity-10',
    projectId: 'project-1',
    taskId: 'task-2',
    userId: 'user-1',
    action: 'task_assigned',
    metadata: { assignedTo: 'user-3' },
    createdAt: '2024-10-02T11:00:00Z',
  },
];
